### ISSUE TITLE
"Defect: unexpected empty zipper while computing range" for some range queries

### ISSUE THREAD

**Issue by mfischerq** [andrewoma/dexx#11]
```java
import com.github.andrewoma.dexx.collection.TreeMap;

public class Test {
	public static void main(String[] args) {
		TreeMap<Integer, String> map = new TreeMap<>();
		map = map.put(new Integer(0), "0");
		map = map.put(new Integer(50), "50");		
		System.out.println(map.to(new Integer(101), false).values());
	}	
}```

This little harmless looking piece of code generates an exception:
java.lang.RuntimeException: Defect: unexpected empty zipper while computing range
	at com.github.andrewoma.dexx.collection.internal.redblack.RedBlackTree.findDepth(RedBlackTree.java:514)
	at com.github.andrewoma.dexx.collection.internal.redblack.RedBlackTree.findDepth(RedBlackTree.java:517)
	at com.github.andrewoma.dexx.collection.internal.redblack.RedBlackTree.rebalance(RedBlackTree.java:533)
	at com.github.andrewoma.dexx.collection.internal.redblack.RedBlackTree.doUntil(RedBlackTree.java:390)
	at com.github.andrewoma.dexx.collection.internal.redblack.RedBlackTree.until(RedBlackTree.java:128)
	at com.github.andrewoma.dexx.collection.TreeMap.to(TreeMap.java:169)

Note that adding another pair, adding the values in a different order or querying for a key that is available prevents the exception from being thrown.

Please fix

**Comment by mfischerq** [comment]
Hi Andrew, 
thank you for fixing this issue so quickly. I tested your fix and can confirm that the issue is solved.

By the way: we are using dexx-collection to implement a datalog engine that supports continuous queries. These are "standing" queries that calculate a change set (insertions/deletions) to the initial query result when data this query relies on is changed. To calculate the change set you need access to the state before and after a change. This is axactly what persistent collections offer out of the box. 
So dexx-collections are very useful for us.
Thanks for maintaining it.

Regards
Martin

**Comment by andrewoma** [comment]
No worries Martin - I was pretty surprised you encountered the bug. I'll push out another release to Maven Central shortly, I just wanted to find a bit more time to test the fix more thoroughly.
